### ISSUE TITLE
Problem with ISTAT data

### ISSUE THREAD

**Issue by madi** [dr-leo/pandaSDMX#120] opened 2019-12-11 15:17 UTC
Hi,

I have a problem trying to download ISTAT metadata. I found no examples but I read that it should be the same as  EUROSTAT, so trying to reproduce EUROSTAT example:

```python
from pandasdmx import Request

# ESTAT example works 
estat = Request('ESTAT')
flow_response = estat.dataflow('edat_aes_l26')
structure_response = flow_response.dataflow.edat_aes_l26.structure(request=True, target_only=False)
structure_response.write().codelist.loc['GEO'].head()

# ISTAT example doesn't work
istat = Request('ISTAT')
# Look at the codes
flow_response = istat.dataflow()
flow_response.dataflow
# Pick code 101_1015
flow_response = istat.dataflow("101_1015")
```

```
HTTPError                                 Traceback (most recent call last)
<ipython-input-77-632709b097fd> in <module>()
----> 1 flow_response = istat.dataflow("101_1015")

/home/madi/.local/lib/python3.6/site-packages/pandasdmx/api.py in get(self, resource_type, resource_id, agency, version, key, params, headers, fromfile, tofile, url, get_footer_url, memcache, writer, dsd, series_keys)
    359             'Requesting resource from URL/file %s', (base_url or fromfile))
    360         source, url, resp_headers, status_code = self.client.get(
--> 361             base_url, params=params, headers=headers, fromfile=fromfile)
    362         if source is None:
    363             raise SDMXException('Server error:', status_code, url)

/home/madi/.local/lib/python3.6/site-packages/pandasdmx/remote.py in get(self, url, fromfile, params, headers)
     96         else:
     97             source, final_url, resp_headers, status_code = self.request(
---> 98                 url, params=params, headers=headers)
     99         return source, final_url, resp_headers, status_code
    100 

/home/madi/.local/lib/python3.6/site-packages/pandasdmx/remote.py in request(self, url, params, headers)
    140             code = int(response.status_code)
    141             if 400 <= code <= 499:
--> 142                 raise response.raise_for_status()
    143             return source, response.url, response.headers, code

/home/madi/.local/lib/python3.6/site-packages/requests/models.py in raise_for_status(self)
    938 
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 
    942     def close(self):

HTTPError: 404 Client Error: Not Found for url: http://sdmx.istat.it/SDMXWS/rest/dataflow/101_1015/latest?references=all
```

**Comment by khaeru** [comment] 2020-01-21 15:28
@madi, thanks for this report! I think it is a duplicate of #75.

Can you please try again using pandaSDMX 1.0.0b2, just released? When I do, I get this:
```python
import pandasdmx as sdmx

istat = sdmx.Request('ISTAT')
flow_msg = istat.dataflow('101_1015')

print(flow_msg)
print(flow_msg.response.url, flow_msg.response.headers)
```

```
$ python3 gh_120.py 
<pandasdmx.StructureMessage>
  <Header>
    id: 'IDREF28448'
    prepared: '2020-01-21T16:20:54.4968933+01:00'
    receiver: 'Unknown'
    sender: 'Unknown'
  response: <Response [200]>
  CategoryScheme (1): ISTAT_DW
  Codelist (10): CL_AGRI_MADRE CL_BASE_YEAR CL_DESTINAZIONEUVA CL_FLAG ...
  ConceptScheme (2): CROSS_DOMAIN VARIAB_ALL
  ContentConstraint (1): CONSTR_101_1015
  DataflowDefinition (1): 101_1015
  DataStructureDefinition (1): DCSP_COLTIVAZIONI
http://sdmx.istat.it/SDMXWS/rest/dataflow/all/101_1015/latest?references=all {'Date': 'Tue, 21 Jan 2020 15:20:54 GMT', 'Server': 'Microsoft-IIS/7.5', 'Cache-Control': 'private', 'Content-Type': 'application/vnd.sdmx.structure+xml; version=2.1; charset=utf-8', 'Accept-Ranges': 'values', 'Vary': 'Accept,Accept-Encoding', 'X-AspNet-Version': '4.0.30319', 'X-Powered-By': 'ASP.NET', 'Via': '1.1 sdmx.istat.it', 'Keep-Alive': 'timeout=10, max=1000', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked'}
```

Note this working URL is different from the one in your pasted report (`dataflow/all/101_1015` instead of `dataflow/101_1015`).

Please let me know if the beta of the 1.0 release fixes this for you, and close the issue if so.

**Comment by dr-leo** [comment] 2020-01-30 22:13
The ISTAT web API seems to be down for an extended period of time. See the review comments in #129

**Closed by dr-leo** 2020-01-30 22:13 UTC
Labels: duplicate, needs info
