### ISSUE TITLE
issue with OECD

### ISSUE THREAD

**Issue by Othello7** [dr-leo/pandaSDMX#40] opened 2016-12-09 16:04 UTC
Hi Dr.Leo,

Thank you so much for your work, it is really useful ! 

I'm using pandasdmx to get data from the OECD.
Unlike other agencies like Eurostat or ECB, i'm struggling with the OECD.
I have these errors but I fail solving it:

- **list of data id:**

When I want to have the list of the dataflow:
flows=oecd.dataflow()
it does not work because the url doesn't exist 
here the error message: 

400 Client Error: Semantic Error for url: http://stats.oecd.org/SDMX-JSON/dataflow/OECD

- **getting the data**

Then when I want to get the data (it does exist) 
resp = Request('OECD').data('TSE_2010', key='ALL', params={'startPeriod': '2007'})
  File "<string>", line unknown
XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

other example:
resp = Request('OECD').data('IDD', key='ALL', params={'startPeriod': '2007'})
  File "<string>", line unknown
XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

Would you help me to solve this problem ? 
I saw on one issue, that your code works for OECD, and I think I have the latest version of your library, so I don't know what I'm doing wrong.

Thank you very much,

Christelle

**Comment by dr-leo** [comment] 2016-12-14 09:40
Hi Christelle,

sorry for responding so late. You are using the most up to date
Version as older ones do not support OECD data at all. You raise some
important Points one of which is a bug:

The JSON representation of SDMX is still being standardized by the
SDMX Technical Working Group. Data Messages have been completed. And
this is what OECD and others have implemented, and what pandaSDMX
should Support with regards to OECD. So your attempt to download a
list of dataflows with metadata as you may have delightfully done from
ECB does not work with OECD as there is no JSON-based Standard for
this which OECD could implement. So you have to explore the available
dataflows on the web. There is no JSON representation for dataflow
definitions either, so a user-provided key to filter columns by
Dimension values will not be validated. All this works only in SDMXML
2.1, not SDMXJSON 2.1. So your missing link is a Feature, not a bug.
Hopefully, the SDMX TWG will get their act together soon and agencies
will add Support for structural metadata in JSON. Thereafter one might
add Support for this in pandaSDMX.

For now, data Messages are the only SDMX Messages pandaSDMX should
Support with regards to OECD. And the error message coming from LXML
is a bug. Sorry. I hope to look into it soon, but I am extremely busy
for now. As a Workaround you may want to try saving the requested data
message to a file ending in .json. Use the 'tofile' keyword Argument
as described in the docs. Then do something like:

req=Request()
data = req.get(fromfile='mydata.json').write()

Pls let me know if this helps. And sorry for flaky testing. My
sparetime I can spend on coding has shrunk dramatically.

Leo

**Comment by dr-leo** [comment] 2016-12-14 11:32
Hi Christelle,

sory. It Looks like the Workaround I was thinking of won't work. I see
where the bug resides. The conditions for selecting the Reader are
incorrect. They work when loading from a file, but not when loading
from OECD over the web.

My apologies for the confusion.

Leo

**Comment by dr-leo** [comment] 2016-12-20 20:53
I've just committed a fix. Please let me know if you still encounter problems.

Leo

**Closed by dr-leo** 2016-12-20 20:53 UTC

**Comment by dr-leo** [comment] 2017-02-06 20:02
Hi,

just to let you know that this is fixed in the current stable release
v0.6.1.

Leo

Am 09.12.2016 um 17:04 schrieb Othello7:
